apiVersion: v1
kind: Service
metadata:
  name: leprechaun-jenkins-blue-test
  namespace: test-project
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    deploymentconfig: leprechaun-jenkins-blue-test
  type: ClusterIP
  sessionAffinity: None
